SET SERVEROUTPUT ON

DECLARE
    NAME VARCHAR2(100);
    LASTNAME VARCHAR2(100);
    PI CONSTANT NUMBER := 3.1416;
    
    A NUMBER := 10;
    B NUMBER := 30;
BEGIN
    NAME:= 'JAMES';
    LASTNAME:= 'BOND';
    DBMS_OUTPUT.PUT_LINE(LASTNAME||'...');
    DBMS_OUTPUT.PUT_LINE(NAME||' '||LASTNAME);
    DBMS_OUTPUT.PUT_LINE('EL VALOR DE PI ES ' || PI);
    DBMS_OUTPUT.PUT_LINE('SUMA ES ' || (A+B));
    B:=NULL;
    DBMS_OUTPUT.PUT_LINE('SUMA ES ' || (A+B));
END;
