SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE VISUALIZAR AS
    CURSOR EMPL_CURR IS
        SELECT FIRST_NAME, SALARY FROM EMPLOYEES;
            
BEGIN
    FOR e IN EMPL_CURR LOOP
        DBMS_OUTPUT.PUT_LINE(e.FIRST_NAME || ': ' || e.SALARY);
    END LOOP;
END;
/

EXECUTE VISUALIZAR;


/

CREATE OR REPLACE PROCEDURE VISUALIZAR_CON_P(d IN NUMBER, res OUT NUMBER) AS
    CURSOR EMPL_CURR IS
        SELECT FIRST_NAME, SALARY FROM EMPLOYEES 
            WHERE department_id=d;
BEGIN
    res:=0;
    FOR e IN EMPL_CURR LOOP
        DBMS_OUTPUT.PUT_LINE(e.FIRST_NAME || ': ' || e.SALARY);
        res:= res+1;
    END LOOP;
END;
/

DECLARE
    DEPA employees.department_id%TYPE;
    res NUMBER;
BEGIN
    DEPA:=10;
    VISUALIZAR_CON_P(10,res);
    DBMS_OUTPUT.PUT_LINE('El numero de empleados en el departamento ' || DEPA || ' es de ' || res);
END;
/

CREATE OR REPLACE PROCEDURE FORMATEAR_CUENTA(CUENTA IN OUT VARCHAR2) AS
    PARTE1 CHAR(4);
    PARTE2 CHAR(4);
    PARTE3 CHAR(2);
    PARTE4 VARCHAR(20);
BEGIN
    PARTE1:=SUBSTR(CUENTA,1,4);
    PARTE2:=SUBSTR(CUENTA,5,4);
    PARTE3:=SUBSTR(CUENTA,9,2);
    PARTE4:=SUBSTR(CUENTA,11);
    DBMS_OUTPUT.PUT_LINE(PARTE1 || '-' || PARTE2 || '-' || PARTE3 || '-' || PARTE4);
END;
/

DECLARE
    CUENTA VARCHAR2(100):='1234567890123456';
BEGIN
    DBMS_OUTPUT.PUT_LINE(CUENTA);
    FORMATEAR_CUENTA(CUENTA);
END;
